server {
    listen 80;
    server_name 10.0.0.60;
    root /var/www/emtservices;
    index index.html;

    location /assets/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
